### ISSUE TITLE
Provision encoding throwing errors

### ISSUE THREAD

**Issue by amozoss** [cisiqo/wbxml#1]
Thanks for the awesome repo! 

I wanted to hear your thoughts on how I could get encoding to work with some provisioning commands.

Here's an example of the commands and the error is commented that I see:

https://github.com/cisiqo/wbxml/compare/main...amozoss:wbxml:main#diff-7fcb44bd2960bb2e2a4a5e84b1bb95f1b3a8f90ea481aa87170958881a11721fR63-R101

The tests are both raising errors. Specifics for each one:

1) It seems like `xmlns:provision="Provision:"` with a `:` is valid, but it's not in wbxml (first test from above).

More specifically from the active sync example https://learn.microsoft.com/en-us/previous-versions/office/developer/exchange-server-interoperability-guidance/hh361570(v=exchg.140)#seeing-it-in-action you can see they use `Provision:`

2) I remove the `:`, but then I'm getting a `** (ArithmeticError) bad argument in arithmetic expression: Bitwise.bor(nil, 64)`

Do you know how I might go about fixing these?

Any help is appreciated. Thanks!

**Comment by cisiqo** [comment]
Thank you.
Issue was fixed.
Please upgrading to 0.1.3

**Comment by amozoss** [comment]
Thanks for the quick fix 

It's working now, appreciate it!
