### ISSUE TITLE
Namespace declaration error - * 1st argument: not an atom

### ISSUE THREAD

**Issue by amozoss** [cisiqo/wbxml#2]
I'm having an issue when doing my sync command. The xml is valid when ran with https://github.com/libwbxml/libwbxml.

I think it's related to namespace declarations

Here's the relevant tests

https://github.com/cisiqo/wbxml/commit/85a36393412186717ae6e92a6cd2692e4cb35669#diff-7fcb44bd2960bb2e2a4a5e84b1bb95f1b3a8f90ea481aa87170958881a11721fR99

I think `Namespace declaration simple` test captures what is failing in the `Namespace declaration` test.

Appreciate any tips on what might be a good way to go about solving this?

**Comment by cisiqo** [comment]
Thank you.
Issue was fixed.
You can try it.
